### Post
POST http://localhost:3200/api/category HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZnVsbG5hbWUiOiJOYXR0YXBvbiBDaG9tc3VudGhpYSIsInVzZXJuYW1lIjoibmF0dGFwb24iLCJjb250YWN0IjoiOTgg4Lir4Lih4Li5IDcg4LiVLuC5guC4leC4meC4lCIsImlhdCI6MTY3NTQxOTMwNSwiZXhwIjoxNjc4MDExMzA1fQ.AJdVo_4UVUeqCtRUo1JfdxSIQcj1qpeAUR-b64qmEFM

{
 "Category_Name": "สุรา",
  "Category_Status": true,
  "Category_Description": "เครื่องดื่มที่มี แอลกอฮอล์"
}